// <auto-generated />
using System;
using ContextMemory.Core.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContextMemory.Api.Migrations
{
    [DbContext(typeof(ContextMemoryDbContext))]
    [Migration("20260525000153_AddCompanyBrain")]
    partial class AddCompanyBrain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.AppProfileEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BusinessRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentRulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FormatRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId");

                    b.ToTable("app_profiles", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.CompanyAppLinkEntity", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CompanyId", "AppId");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("company_app_links", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.CompanyEntity", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillsCacheJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.CompanyKnowledgeSourceEntity", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyId", "SourceId");

                    b.ToTable("company_knowledge_sources", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.CompanyProcessEntity", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProcessId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompanyId", "ProcessId");

                    b.ToTable("company_processes", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.ConversationHistoryEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionSummary")
                        .HasColumnType("text");

                    b.HasKey("AppId", "UserId");

                    b.ToTable("conversation_history", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.FeedbackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsImplicit")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Timestamp");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.RegisteredAppEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikiPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId");

                    b.ToTable("registered_apps", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.SemanticFactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LearnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "UserId");

                    b.ToTable("semantic_facts", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Core.Persistence.Postgres.UserProfileEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionContext")
                        .HasColumnType("text");

                    b.HasKey("AppId", "UserId");

                    b.ToTable("user_profiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
